### ISSUE TITLE
Exception in thread "pool-1-thread-1" java.lang.NullPointerException: Null concepts

### ISSUE THREAD

**Issue by memuyskens** [Clarifai/clarifai-java#46]
This is my request:
![screen shot 2017-06-13 at 3 40 51 pm](https://user-images.githubusercontent.com/11319843/27101192-b9520260-504e-11e7-99a2-a15d7e63f5b4.png)

Despite receiving expected responses that work just fine for us, this stack trace is printed from one of your classes:

![screen shot 2017-06-13 at 9 16 24 am](https://user-images.githubusercontent.com/11319843/27101136-7bde24b8-504e-11e7-808d-35dffbe7652c.png)

Is this an expected side effect or are we missing an important detail within our implementation of a request?

**Comment by saurav12994** [comment]
I also get same error

**Comment by nikhil-pandita** [comment]
Same Error here :
 java.lang.NullPointerException: Null concepts
                                                                                at clarifai2.dto.model.output_info.$AutoValue_ConceptOutputInfo.<init>($AutoValue_ConceptOutputInfo.java:24)
                                                                                at clarifai2.dto.model.output_info.AutoValue_ConceptOutputInfo.<init>(AutoValue_ConceptOutputInfo.java:11)
                                                                                at clarifai2.dto.model.output_info.ConceptOutputInfo$Adapter$2.deserialize(ConceptOutputInfo.java:122)
                                                                                at clarifai2.dto.model.output_info.ConceptOutputInfo$Adapter$2.deserialize(ConceptOutputInfo.java:93)
                                                                                at clarifai2.internal.JSONAdapterFactory$Adapter.read(JSONAdapterFactory.java:173)
                                                                                at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
                                                                                at com.google.gson.Gson.fromJson(Gson.java:887)
                                                                                at com.google.gson.Gson.fromJson(Gson.java:952)
                                                                                at com.google.gson.Gson.fromJson(Gson.java:925)
                                                                                at clarifai2.internal.InternalUtil.fromJson(InternalUtil.java:153)
                                                                                at clarifai2.dto.model.output_info.OutputInfo$Adapter$1.deserialize(OutputInfo.java:39)
                                                                                at clarifai2.dto.model.output_info.OutputInfo$Adapter$1.deserialize(OutputInfo.java:25)
                                                                                at clarifai2.internal.JSONAdapterFactory$Adapter.read(JSONAdapterFactory.java:173)
                                                                                at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
                                                                                at com.google.gson.Gson.fromJson(Gson.java:887)
                                                                                at com.google.gson.Gson.fromJson(Gson.java:952)
                                                                                at com.google.gson.Gson.fromJson(Gson.java:925)
                                                                                at clarifai2.internal.InternalUtil.fromJson(InternalUtil.java:153)
                                                                                at clarifai2.dto.model.Model$Adapter$2.deserialize(Model.java:219)
                                                                                at clarifai2.dto.model.Model$Adapter$2.deserialize(Model.java:196)
                                                                                at clarifai2.internal.JSONAdapterFactory$Adapter.read(JSONAdapterFactory.java:173)
                                                                                at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
                                                                                at com.google.gson.Gson.fromJson(Gson.java:887)
                                                                                at com.google.gson.Gson.fromJson(Gson.java:952)
                                                                                at clarifai2.api.request.model.GetModelRequest$1$1.fromJSON(GetModelRequest.java:34)
                                                                                at clarifai2.api.request.model.GetModelRequest$1$1.fromJSON(GetModelRequest.java:32)
                                                                                at clarifai2.api.request.ClarifaiRequest$Impl.executeSync(ClarifaiRequest.java:285)
                                                                                at clarifai2.api.request.ClarifaiRequest$Builder.executeSync(ClarifaiRequest.java:192)
                                                                                at clarifai2.dto.model.DefaultModels.update(DefaultModels.java:60)
                                                                                at clarifai2.dto.model.DefaultModels.access$000(DefaultModels.java:10)
                                                                                at clarifai2.dto.model.DefaultModels$1.run(DefaultModels.java:50)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                at java.lang.Thread.run(Thread.java:818)

**Comment by mgoovaer** [comment]
Same here!

**Comment by mglad** [comment]
I am having this issue as well :+1:

**Comment by josh-tepper** [comment]
We've resolved the issue.  There was a bug in our API that was causing `GET /v2/models/{{model_id}}/output_info` to return Models with an output_info that is invalid. The Java client code not properly deserialize these invalid output_info objects.

**Comment by memuyskens** [comment]
So, to clarify (pun intended), we will not need to update our dependencies to use a newer version of your Java client API? This was an issue on your side?

**Comment by memuyskens** [comment]
I appreciate the quick fix and reply.
Thank you!
