### ISSUE TITLE
NullPointer Exception

### ISSUE THREAD

**Issue by Amee-h** [Clarifai/clarifai-java#55]
Hi,
I have tried **faceDetectionModel** with below request

> **client.getDefaultModels().faceDetectionModel().predict().withInputs(ClarifaiInput.forImage(ClarifaiImage.of(image))).executeSync()**

and image passed as a parameter was **https://developer.clarifai.com/static/images/model-samples/face-001.jpg**    and then
I am getting **nullpointer exception** with
at clarifai2.dto.prediction.Region$Adapter$1.deserialize(Region.java:53)
	at clarifai2.dto.prediction.Region$Adapter$1.deserialize(Region.java:38)
	at clarifai2.internal.JSONAdapterFactory$Adapter.read(JSONAdapterFactory.java:173)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:952)
	at com.google.gson.Gson.fromJson(Gson.java:925)
	at clarifai2.internal.InternalUtil.fromJson(InternalUtil.java:153)
	at clarifai2.dto.model.output.ClarifaiOutput$Adapter$1.deserialize(ClarifaiOutput.java:94)
	at clarifai2.dto.model.output.ClarifaiOutput$Adapter$1.deserialize(ClarifaiOutput.java:54)
	at clarifai2.internal.JSONAdapterFactory$Adapter.read(JSONAdapterFactory.java:173)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:952)
	at clarifai2.internal.InternalUtil.fromJson(InternalUtil.java:162)
	at clarifai2.api.request.model.PredictRequest$1$3.fromJSON(PredictRequest.java:134)
	at clarifai2.api.request.model.PredictRequest$1$3.fromJSON(PredictRequest.java:131)
	at clarifai2.api.request.ClarifaiRequest$Impl.executeSync(ClarifaiRequest.java:285)
	at clarifai2.api.request.ClarifaiRequest$Builder.executeSync(ClarifaiRequest.java:192)

**Comment by rok-povsic** [comment]
Hi @Amee-h, 

Thank you for reporting this. This will be fixed in the next release.

**Comment by josh-tepper** [comment]
This is resolved by the 2.3 release, currently available.
